server:
  port: 8086
  servlet:
    context-path: /edusys



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/edusys?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhangcan123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


#  redis:
#    database: 3
#    host: localhost
#    port: 6379
#    password:
#    timeout: 5000
#    jedis:
#      pool:
#        max-wait: -1
#        max-active: 1000
#        max-idle: 10
#        min-idle: 2

#  mail:
#    host: smtp.126.com
#    username: sslmzc@126.com
#    password: sslmzc123
#    default-encoding: UTF-8



#  thymeleaf:
#    prefix: /templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: true

  messages:
    basename: i18/messages
    cache-duration: 3600
    encoding: UTF-8

